FROM public.ecr.aws/lambda/python:3.13
ENV TZ=America/New_York

# Copy requirements.txt
COPY lambda/* ${LAMBDA_TASK_ROOT}
# COPY lambda/requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy all files in ./src
RUN mkdir -p ${LAMBDA_TASK_ROOT}/src
COPY src/ ${LAMBDA_TASK_ROOT}/src

# Set the CMD to your handler.
CMD [ "lambda_function.lambda_handler" ]