
# You can include the filters, mergers, formatters, and processors in septate config files.
# Those config files are included in the job config file.
# include: 
#   - "bursar_transfer_filters.yaml"
#   - "bursar_transfer_mergers.yaml"
#   - "bursar_transfer_formatters.yaml"
#   - "bursar_transfer_exporters.yaml"
#   - "bursar_transfer_processors.yaml"

# variables can be defined in the job config file or in the included config files.
# The variables defined in the job config file pass down to the included config files.
# vars:
#   run_env: "TEST"
#   trans_active: true
#
# variables can be used as follows:
#   - name: "${run_env}"


max_fines_to_be_pulled: 100000 # Maximum number of fine records to be pulled from the FOLIO system  
charge_days_outstanding: 30 # Number of days the fine must be outstanding to be included in the export
charges_max_age: 365  # Maximum age of the fine in days to be included in the export
credit_days_outstanding: 6 # Number of days the credit must have been created to be included in the export


filters:
  charge_filters:
    - name: "FineType"
      error_message: "Wrong Fee Fine Type"
      load: "FeeFineTypes"
      flatten: true
      filter_field: "feeFineId"
      field_transform: "NONE"
      filter_operator: "IN_FILE"
      filter_value: ""
      log_error: false
    - name: "BursarActive"
      error_message: "Exports suspended for user"
      load: false
      flatten: false
      filter_field: "patron.customFields.bursar"
      field_transform: "NONE"
      filter_operator: "NULL_OR_ONE_OF"
      filter_value: 
        - 'opt_0'
      log_error: true
  credit_filters:
    - name: "BadExternalID"
      error_message: "The external ID is not valid"
      load: false
      flatten: false
      filter_field: "patron.externalSystemId"
      field_transform: "COUNT"
      filter_operator: "SHORTER_THAN"
      filter_value: 10
      log_error: true
  process_filter:

mergers:
  charge_mergers:
    - merge_type: "FIELD"
      load: false
      filter_field: false
      new_field: "fee_owner_id"
      field_1: "ownerId"
      field_2: "feeFineId"
      field_deliminator: "|"
      field_transform: "NONE"
  credit_mergers:
    - merge_type: "FIELD"
      load: false
      filter_field: false
      new_field: "fee_owner_id"
      field_1: "ownerId"
      field_2: "feeFineId"
      field_deliminator: "|"
      field_transform: "NONE"

formatters:
  charge_formatters:
    - filter_field:"patron.externalSystemId", 
      type:"LEFT_STRIP", 
      search_for:"0", 
      replace_with:"", 
      new_field:"patron.externalSystemId"
  credit_formatters:
    - filter_field:"patron.externalSystemId", 
      type:"LEFT_STRIP", 
      search_for:"0", 
      replace_with:"", 
      new_field:"patron.externalSystemId"

processors:
  - name: "Transfer"
    action_type: "TRANSFER"
    payment_method: "Bursar"
    service_point_id: "7495d2e3-1e4b-4b6d-9f3b-1f4b1f0b1b6d"
    user_name: "app_test"
    comments: "STAFF : automated system"
    filters: 
        -   name: "FineType"
            error_message: "Wrong Fee Fine Type"
            load: "FeeFineTypes"
            flatten: true
            filter_field: "feeFineId"
            field_transform: "NONE"
            filter_operator: "IN_FILE"
            filter_value: ""
            log_error: false
    stop_processing: true
    process_active: true

export:
  - file_name: "charges_{{format_date 'NOW' '%Y%m%d'}}.csv"
    template_name: "charges"
    template_data: "CHARGE_DATA"
    export_type: "S3"
    export_to: ""
    connection_name: "AWS_1"
    attachment: false
  - file_name: "Report summary {{format_date 'NOW' '%Y%m%d'}}" # Sample of an email with an attachment
    template_name: "email_body"
    template_data: "CHARGE_DATA"
    export_type: "EMAIL"
    export_to: "james@institution.com"
    connection_name: "AWS_1"
    attachment: 
    - file_name: "charges_{{format_date 'NOW' '%Y%m%d'}}.csv"
      file_append_date: true
      date_format: "%Y%m%d"
      template_name: "charges"
      template_data: "CHARGE_DATA"

connectors:
  - name: "Airtable"
    connection_name: "AIR_TABLE_1"
    connector_type: "AIRTABLE"
    mapping_type: "INLINE"
    connector_action: "CREATE"
    field_data: "CHARGE_DATA"
    field_mapping:
      - field_name: "External ID"
        field_source: "patron.externalSystemId"
        field_type: "DYNAMIC"
      - field_name: "First Name"
        field_source: "patron.firstName"
        field_type: "DYNAMIC"
      - field_name: "Last Name"
        field_source: "patron.lastName"
        field_type: "DYNAMIC"
      - field_name: "Uploaded"
        field_type: "DATE"
        field_format: "%Y%m%d"
      - field_name: "Note"
        field_type: "STATIC"
        field_format: "This was added by the transfer automation system"
  - name: "Airtable"
    connection_name: "AIR_TABLE_1"
    connector_type: "AIRTABLE"
    mapping_type: "INLINE"
    connector_action: "UPDATE"
    field_data: "CHARGE_DATA"
    filter_filed: "External ID"
    field_mapping:
      - field_name: "External ID"
        field_source: "patron.externalSystemId"
        field_type: "DYNAMIC"
      - field_name: "First Name"
        field_source: "patron.firstName"
        field_type: "DYNAMIC"
  - name: "Airtable"
    connection_name: "AIR_TABLE_1"
    connector_type: "AIRTABLE"
    connector_action: "DELETE"
    field_data: "CHARGE_DATA"
    filter_filed: "External ID"
    filter_value: "patron.externalSystemId"
  - name: "Bursar API"
    connection_name: "AWS_1"
    connector_type: "SHAREPOINT"
    mapping_type: "TEMPLATE"
    field_data: "CHARGE_DATA"
    field_template: "bursar_template"